version: '3.6'

x-shared-environment: &commonEnv
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_HOST: "rdbms_obs"
    POSTGRES_DB: "soa"

services:
    ui_obs:
        container_name: 'ui_obs'
        build:
          context: './ui'
          args:
            NODE_ENV: 'production'
            REACT_APP_HOST_API: 'http://localhost:8080/api/v1'
        ports:
          - '80:80'
        networks:
          - operational_network
    api_obs:
        container_name: 'api_obs'
        build: './DOS/soa'
        ports:
          - '8080:80'
        environment: *commonEnv
        networks:
          - operational_network
    rdbms_obs:
        container_name: 'rdbms_obs'
        image: 'debezium/postgres'
        ports:
          - '5432:5432'
        environment: *commonEnv
        volumes:
          - serv_obs_pg_data:/var/lib/postgresql/data
        networks:
          - operational_network
    sso_obs:
        container_name: 'sso_obs'
        build: './DOS/sso'
        ports:
          - '10090:10090'
        environment: *commonEnv
        networks:
          - operational_network

networks:
    operational_network:
        name: operational_network
        driver: bridge


volumes:
    serv_obs_pg_data:
