version: '3.6'

x-shared-environment: &commonEnv
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_PORT: 5432
    POSTGRES_HOST: "rdbms_obs"
    POSTGRES_DB: "soa"

services:
    ui_obs:
        container_name: 'ui_obs'
        build: './ui'
        ports:
          - '3000:80'
    api_obs:
        container_name: 'api_obs'
        build: './soa'
        ports:
          - '8080:8080'
        environment: *commonEnv
        networks:
          - operational_network
    rdbms_obs:
        container_name: 'rdbms_obs'
        image: 'debezium/postgres'
        ports:
          - '5432:5432'
        environment: *commonEnv
        volumes:
          - serv_obs_pg_data:/var/lib/postgresql/data
        networks:
          - operational_network
    cube_render:
        container_name: 'cube_render'
        build: './DWH/cube_render'
        ports:
          - '10070:10070'
        environment: *commonEnv
        networks:
          - operational_network

networks:
    operational_network:
        name: operational_network
        driver: bridge


volumes:
    serv_obs_pg_data:
